; PlatformIO Project Configuration File — Vision_NODE
;
; Sala de Estudo Inteligente — Nó de Visão (AI-Thinker ESP32-CAM + OV2640)

[env:esp32cam]
platform      = espressif32
board         = esp32cam
framework     = arduino
monitor_speed = 115200
upload_speed  = 921600

board_build.partitions = huge_app.csv

lib_deps =
	mobizt/Firebase Arduino Client Library for ESP8266 and ESP32 @ ^4.4.14

build_flags =
	-D CORE_DEBUG_LEVEL=3
	-D BOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
